# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  username: anali
  password: "1tesla"
  host: localhost
  pot: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_development

test:
  <<: *default
  database: project_test

production:
  <<: *default
  database: project_production
  username: anali
  password: "1tesla"

